### ISSUE TITLE
Numeric string starting with 0 is converted to a number instead of a string

### ISSUE THREAD

**Issue by Semalexa** [HealthSamurai/jute.clj#28]
Number:
![2022-11-08_08-24_08](https://user-images.githubusercontent.com/345535/200828397-60a2a084-7421-4593-80f2-58fc8d98ab50.png)

String:
![2022-11-08_08-24_19](https://user-images.githubusercontent.com/345535/200828410-a32dc1c7-4130-43fa-a2fd-5f857ee553df.png)

Template:
```
resourceType: Patient
id: '$ patientId'        
identifier:
  - system: 'http://fhir.ru/core/systems/snils'
    value: '$ patientSNILS'
    type:
      coding:
      - system: http://terminology.hl7.org/CodeSystem/v2-0203
        code: SB
        display: Social Beneficiary Identifier
  - system: 'http://fhir.ru/core/systems/passport-rf'
    value: '$ patientCardNumber'
```

Source:
```
{
  "templateId": "1.2.643.5.1.13.13.14.113.9.2",
  "title": "СТАТИСТИЧЕСКАЯ КАРТА ВЫБЫВШЕГО ИЗ СТАЦИОНАРА",
  "confidentialityCode": "N",
  "id": "744640",
  "setId": "999",
  "versionNumber": 1,
  "patientId": "0b16d46d-3a32-4af2-8eff-f1ae4ec2a0e8",
  "patientSNILS": "36352463277",
  "patientCardType": "1",
  "patientCardSeries": "941968374",
  "patientCardNumber": "941968374"}
```

Result:
```
resourceType: Patient
id: 0b16d46d-3a32-4af2-8eff-f1ae4ec2a0e8
identifier:
  - system: 'http://fhir.ru/core/systems/snils'
    value: '36352463277'
    type:
      coding:
        - system: 'http://terminology.hl7.org/CodeSystem/v2-0203'
          code: SB
          display: Social Beneficiary Identifier
  - system: 'http://fhir.ru/core/systems/passport-rf'
    value: 041968374
```
