### ISSUE TITLE
toInt converts string only, impossible to convert dec to int

### ISSUE THREAD

**Issue by ruscoder** [HealthSamurai/jute.clj#29]
Hi!
```myint: $ toInt(185.5)``` always returns 185.5

**Comment by ruscoder** [comment]
Workaround:
```
  decToInt:
    $fn:
      - x
    $name: decToInt
    $body: $ toInt(replace(toString(x), '\..+', ''))
```
